n: [20,50,100,500]
t: [20,40,60,80]
viol_mult: [0,1,10,100]
sim_reps: 3
accessibility_mask: "https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/working/20160622_genome_mask_GRCh38/StrictMask/20160622.allChr.mask.bed"
scm_reps: 1000
pop_size: 10000
rsimpop_repo: "https://github.com/nangalialab/rsimpop.git"
rsimpop_commit: "dc76d53618c96ac831a90ebe1250e2b3ae73293c"
cellphy_repo: "https://github.com/amkozlov/cellphy.git"
cellphy_commit: "bcb73f6e4cd549726328837e1773a6f3582450c0"