input:
  vcfs:
    sampleA: "/path/to/sampleA.vcf"
    sampleB: "/path/to/sampleB.vcf"
  trees:
    sampleA: "/path/to/sampleA.cellphy.supportFBP"
    sampleB: "/path/to/sampleB.cellphy.supportFBP"
  outgroup:
    sampleA: "sampleA_outgroup"
    sampleB: "sampleB_outgroup"
  models:
    sampleA: "/path/to/sampleA_gt10.cellphy.model"
    sampleB: "/path/to/sampleB_gt10.cellphy.model"
run_params:
  n_threads: 4
  n_replicates: 100
  mem_mb: 16000